namespace PAL
{
    using System;

    public class BusinessPAL
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string ABN { get; set; }
        public string StreetAddress { get; set; }
        public string Location { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string BusinessPhone { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string ProfilePhoto { get; set; }
        public int ProfilePhotoID { get; set; }
        public string Description { get; set; }
        public string AboutUs { get; set; }
        public string StoreName { get; set; }
        public string BSBNo { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string AccountName { get; set; }
        public int Status { get; set; }
        public string BusinessType { get; set; }
        public string DietryIDs { get; set; }        
        public bool IsProfileDetails { get; set; }
        public string FoodItems { get; set; }
        public string RestaurantTypes { get; set; }
        public int MondayScheduleOn { get; set; }
        public int MondayNoOfItems { get; set; }
        public decimal MondayOriginalPrice { get; set; }
        public decimal MondayDiscount { get; set; }
        public string MondayFromTime { get; set; }
        public string MondayToTime { get; set; }
        public int TuesdayScheduleOn { get; set; }
        public int TuesdayNoOfItems { get; set; }
        public decimal TuesdayOriginalPrice { get; set; }
        public decimal TuesdayDiscount { get; set; }
        public string TuesdayFromTime { get; set; }
        public string TuesdayToTime { get; set; }
        public int WednesdayScheduleOn { get; set; }
        public int WednesdayNoOfItems { get; set; }
        public decimal WednesdayOriginalPrice { get; set; }
        public decimal WednesdayDiscount { get; set; }
        public string WednesdayFromTime { get; set; }
        public string WednesdayToTime { get; set; }
        public int ThirsdayScheduleOn { get; set; }
        public int ThirsdayNoOfItems { get; set; }
        public decimal ThirsdayOriginalPrice { get; set; }
        public decimal ThirsdayDiscount { get; set; }
        public string ThirsdayFromTime { get; set; }
        public string ThirsdayToTime { get; set; }
        public int FridayScheduleOn { get; set; }
        public int FridayNoOfItems { get; set; }
        public decimal FridayOriginalPrice { get; set; }
        public decimal FridayDiscount { get; set; }
        public string FridayFromTime { get; set; }
        public string FridayToTime { get; set; }
        public int SaturdayScheduleOn { get; set; }
        public int SaturdayNoOfItems { get; set; }
        public decimal SaturdayOriginalPrice { get; set; }
        public decimal SaturdayDiscount { get; set; }
        public string SaturdayFromTime { get; set; }
        public string SaturdayToTime { get; set; }
        public int SundayScheduleOn { get; set; }
        public int SundayNoOfItems { get; set; }
        public decimal SundayOriginalPrice { get; set; }
        public decimal SundayDiscount { get; set; }
        public string SundayFromTime { get; set; }
        public string SundayToTime { get; set; }
        public string MondaySchedule { get; set; }
        public string TuesdaySchedule { get; set; }
        public string WednesdaySchedule { get; set; }
        public string ThirsdaySchedule { get; set; }
        public string FridaySchedule { get; set; }
        public string SaturdaySchedule { get; set; }
        public string SundaySchedule { get; set; }
        public string Monday2Schedule { get; set; }
        public string Tuesday2Schedule { get; set; }
        public string Wednesday2Schedule { get; set; }
        public string Thirsday2Schedule { get; set; }
        public string Friday2Schedule { get; set; }
        public string Saturday2Schedule { get; set; }
        public string Sunday2Schedule { get; set; }
        public string Monday3Schedule { get; set; }
        public string Tuesday3Schedule { get; set; }
        public string Wednesday3Schedule { get; set; }
        public string Thirsday3Schedule { get; set; }
        public string Friday3Schedule { get; set; }
        public string Saturday3Schedule { get; set; }
        public string Sunday3Schedule { get; set; }
        public string AuthToken { get; set; }
        public int NoOfItems { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal DiscountID { get; set; }
        public DateTime PickupFromTime { get; set; }
        public DateTime PickupToTime { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string PostCode { get; set; }
        public int GSTregistered { get; set; }
        public int ReceiveMarketingMails { get; set; }
        public string PasswordOTP { get; set; }
        public string StoreImages { get; set; }
        public string OTP { get; set; }
        public string NewPassword { get; set; }
        public string Note { get; set; }
        public byte RegisterGst { get; set; }
        public byte CategoryTaxItemOrNot { get; set; }
        public string DeviceToken { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
    }

    public class BusinessPALAdminScreen
    {
        public long ID { get; set; }
        public string BusinessName { get; set; }
        public string Location { get; set; }
        public string AccountName { get; set; }
        public string State { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessMobile { get; set; }
        public string StreetAddress { get; set; }
        public string EmailAddress { get; set; }
        public string ABN { get; set; }
        public string BSBNo { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string ProfilePhoto { get; set; }
        public string AboutUs { get; set; }
        public string Description { get; set; }
        public string SelectedCategory { get; set; }
        public string SelectedBusiness { get; set; }
        public string SelectedDietTypes { get; set; }
        public string StorePhoto { get; set; }
        public DateTime CurrentDate { get; set; }
        public int? CurrentDayNoOfItems1 { get; set; }
        public decimal? CurrentDayOriginalPrice1 { get; set; }
        public decimal? CurrentDayDiscount1 { get; set; }
        public int? CurrentDayNoOfItems2 { get; set; }
        public decimal? CurrentDayOriginalPrice2 { get; set; }
        public decimal? CurrentDayDiscount2 { get; set; }
        public int? CurrentDayNoOfItems3 { get; set; }
        public decimal? CurrentDayOriginalPrice3 { get; set; }
        public decimal? CurrentDayDiscount3 { get; set; }
        public string CurrentDayFromTime { get; set; }
        public string CurrentDayToTime { get; set; }
        public string MondayPickUpFromTime { get; set; }
        public string MondayPickUpToTime { get; set; }
        public int? MondayNoOfItems1 { get; set; }
        public decimal? MondayOriginalPrice1 { get; set; }
        public decimal? MondayDiscount1 { get; set; }
        public int? MondayNoOfItems2 { get; set; }
        public decimal? MondayOriginalPrice2 { get; set; }
        public decimal? MondayDiscount2 { get; set; }
        public int? MondayNoOfItems3 { get; set; }
        public decimal? MondayOriginalPrice3 { get; set; }
        public decimal? MondayDiscount3 { get; set; }
        public string TuesdayPickUpFromTime { get; set; }
        public string TuesdayPickUpToTime { get; set; }
        public int? TuesdayNoOfItems1 { get; set; }
        public decimal? TuesdayOriginalPrice1 { get; set; }
        public decimal? TuesdayDiscount1 { get; set; }
        public int? TuesdayNoOfItems2 { get; set; }
        public decimal? TuesdayOriginalPrice2 { get; set; }
        public decimal? TuesdayDiscount2 { get; set; }
        public int? TuesdayNoOfItems3 { get; set; }
        public decimal? TuesdayOriginalPrice3 { get; set; }
        public decimal? TuesdayDiscount3 { get; set; }
        public string WednesdayPickUpFromTime { get; set; }
        public string WednesdayPickUpToTime { get; set; }
        public int? WednesdayNoOfItems1 { get; set; }
        public decimal? WednesdayOriginalPrice1 { get; set; }
        public decimal? WednesdayDiscount1 { get; set; }
        public int? WednesdayNoOfItems2 { get; set; }
        public decimal? WednesdayOriginalPrice2 { get; set; }
        public decimal? WednesdayDiscount2 { get; set; }
        public int? WednesdayNoOfItems3 { get; set; }
        public decimal? WednesdayOriginalPrice3 { get; set; }
        public decimal? WednesdayDiscount3 { get; set; }
        public string ThursdayPickUpFromTime { get; set; }
        public string ThursdayPickUpToTime { get; set; }
        public int? ThursdayNoOfItems1 { get; set; }
        public decimal? ThursdayOriginalPrice1 { get; set; }
        public decimal? ThursdayDiscount1 { get; set; }
        public int? ThursdayNoOfItems2 { get; set; }
        public decimal? ThursdayOriginalPrice2 { get; set; }
        public decimal? ThursdayDiscount2 { get; set; }
        public int? ThursdayNoOfItems3 { get; set; }
        public decimal? ThursdayOriginalPrice3 { get; set; }
        public decimal? ThursdayDiscount3 { get; set; }
        public string FridayPickUpFromTime { get; set; }
        public string FridayPickUpToTime { get; set; }
        public int? FridayNoOfItems1 { get; set; }
        public decimal? FridayOriginalPrice1 { get; set; }
        public decimal? FridayDiscount1 { get; set; }
        public int? FridayNoOfItems2 { get; set; }
        public decimal? FridayOriginalPrice2 { get; set; }
        public decimal? FridayDiscount2 { get; set; }
        public int? FridayNoOfItems3 { get; set; }
        public decimal? FridayOriginalPrice3 { get; set; }
        public decimal? FridayDiscount3 { get; set; }
        public string SaturdayPickUpFromTime { get; set; }
        public string SaturdayPickUpToTime { get; set; }
        public int? SaturdayNoOfItems1 { get; set; }
        public decimal? SaturdayOriginalPrice1 { get; set; }
        public decimal? SaturdayDiscount1 { get; set; }
        public int? SaturdayNoOfItems2 { get; set; }
        public decimal? SaturdayOriginalPrice2 { get; set; }
        public decimal? SaturdayDiscount2 { get; set; }
        public int? SaturdayNoOfItems3 { get; set; }
        public decimal? SaturdayOriginalPrice3 { get; set; }
        public decimal? SaturdayDiscount3 { get; set; }
        public string SundayPickUpFromTime { get; set; }
        public string SundayPickUpToTime { get; set; }
        public int? SundayNoOfItems1 { get; set; }
        public decimal? SundayOriginalPrice1 { get; set; }
        public decimal? SundayDiscount1 { get; set; }
        public int? SundayNoOfItems2 { get; set; }
        public decimal? SundayOriginalPrice2 { get; set; }
        public decimal? SundayDiscount2 { get; set; }
        public int? SundayNoOfItems3 { get; set; }
        public decimal? SundayOriginalPrice3 { get; set; }
        public decimal? SundayDiscount3 { get; set; }

    }
}